title: K's Map | DeePunk's Blog
favicon: /icon.png
icon: /icon.png

menu:
  about: /about

copyright: 2021 DeePunk

giscus:
  enable: true
  repo: DeePunk42/DeePunk42.github.io
  repoID: R_kgDOJkjY4A
  category: Announcements
  categoryID: DIC_kwDOJkjY4M4DEKmV
  mapping: pathname
  strict: 0
  reactionsEnabled: 1
  emitMetadata: 0
  inputPosition: bottom
  lang: zh-CN
  loading: lazy

rss: /atom.xml
